config/routes.rb
Neighborly::Admin::Engine.routes.draw do
  root to: 'dashboard#index'
  resources :tags, except: [:show]
  resources :press_assets, except: [:show]
  resources :financials, only: [ :index ]
  resources :users, only: [ :index ]

  resources :channels, except: [:show] do
    member do
      put 'push_to_draft'
      put 'push_to_online'
    end

    resources :members, only: [:index, :new, :create, :destroy], controller: 'channels/members'
  end

  resources :projects, only: [ :index, :update, :destroy ] do
    member do
      put 'launch'
      put 'reject'
      put 'push_to_draft'
      put 'approve'
      get 'populate_contribution'
      post 'populate'
    end
  end

  resources :contributions, only: [ :index, :update ] do
    member do
      put 'confirm'
      put 'pendent'
      put 'change_reward'
      put 'refund'
      put 'hide'
      put 'cancel'
      put 'push_to_trash'
    end
  end

  namespace :reports do
    resources :contribution_reports, only: [ :index ]
    resources :funding_raised_per_project_reports, only: [ :index ]
    resources :statistics, only: [ :index ]
  end

  resources :contacts, only: [:index, :show]
end

app/controllers/neighborly/admin/channels/members_controller.rb
module Neighborly::Admin
  class Channels::MembersController < BaseController
    actions :index
    helper_method :parent

    def new; end

    def create
      if params[:user_id].present?
        user = User.find(params[:user_id]) rescue nil

        if user.present?
          if parent.members.include?(user)
            flash.alert = t('neighborly.admin.channels.members.messages.already_a_member')
          else
            parent.members << user
            parent.save
            flash.notice = t('neighborly.admin.channels.members.messages.success')
          end
        else
          flash.alert = t('neighborly.admin.channels.members.messages.user_not_found')
        end
      end

      redirect_to channel_members_path(parent)
    end

    def destroy
      parent.channel_members.where(user_id: resource.id).first.delete rescue false
      redirect_to channel_members_path(parent), flash: { success: t('neighborly.admin.channels.members.messages.removed') }
    end

    protected
    def resource
      @member ||= parent.members.find(params[:id])
    end

    def parent
      @channel ||= Channel.find_by_permalink params[:channel_id]
    end

    def collection
      @members ||= parent.members.page(params[:page])
    end
  end
end

app/controllers/neighborly/admin/channels_controller.rb
module Neighborly::Admin
  class ChannelsController < BaseController
    defaults finder: :find_by_permalink
    actions :all, except: [:show]

    def create
      create! { channels_path }
    end

    def update
      update! { channels_path }
    end

    def destroy
      destroy! { channels_path }
    end

    def self.channel_actions
      %w[push_to_draft push_to_online].each do |action|
        define_method action do
          resource.send(action)
          flash.notice = I18n.t("neighborly.admin.channels.messages.successful.#{action}")
          redirect_to channels_path(params[:local_params])
        end
      end
    end
    channel_actions

    protected
    def collection
      @channels = apply_scopes(end_of_association_chain).order(:name).page(params[:page])
    end

    def permitted_params
      user_attrs = [user_attributes: User.attribute_names.map(&:to_sym)]
      aditional_attrs = [start_content: params.try(:[], :channel).
                                               try(:[], :start_content).
                                               try(:keys),

                         success_content: params.try(:[], :channel).
                                               try(:[], :success_content).
                                               try(:keys),]
      params.permit({ channel:
                      Channel.attribute_names.map(&:to_sym) +
                      user_attrs +
                      aditional_attrs })
    end
  end
end

app/views/neighborly/admin/channels/_form.html.slim
= simple_form_for  resource, url: (resource.persisted? ? channel_path(resource) : channels_path) do |form|
  - resource.build_user unless resource.user.present?

  - unless resource.persisted?
    .row
      .large-6.columns.existing-user
        .row
          .large-12.columns
            h5 = t('.associate_existing_user')
            = form.input :user_id, as: :integer, required: false

      .large-6.columns.new-user
        = form.fields_for :user do |uf|
          .row
            .large-12.columns
              h5 = t('.create_new_channel_user')
              = uf.input :email, as: :string, required: false
            .large-12.columns
              = uf.input :password, as: :password


  .row
    .large-10.columns
      = form.input :permalink, as: :string
    .large-2.columns
      br/
      = form.input :accepts_projects
  = form.input :name, as: :string
  .row
    .large-9.columns
      = form.input :description, as: :text
    .large-3.columns
      = form.input :image, as: :file
      - if resource.image.present?
        p= image_tag(resource.image.thumb.url)
  .row
    - if resource.persisted?
      .large-6.small-6.columns
        = form.fields_for :user do |uf|
          = uf.input :email, as: :string
    .large-6.small-6.columns
      = form.input :video_url, as: :string
  .row
    .large-4.columns
      .row.collapse
        .small-3.large-2.columns
          span class="prefix"
            i.icon-et-facebook
        .small-9.large-10.columns
          = form.fields_for :user do |uf|
            = uf.input :facebook_url, input_html: { class: "with-prefix" }, label: false, as: :string
    .large-4.columns
      .row.collapse
        .small-3.large-2.columns
          span class="prefix"
            i.icon-et-twitter
        .small-9.large-10.columns
          = form.fields_for :user do |uf|
            = uf.input :twitter_url, input_html: { class: "with-prefix" }, label: false, as: :string
    .large-4.columns
      .row.collapse
        .small-3.large-2.columns
          span class="prefix"
            i.icon-et-globe
        .small-9.large-10.columns
          = form.fields_for :user do |uf|
            = uf.input :other_url, input_html: { class: "with-prefix" }, label: false, as: :string

  = form.input :submit_your_project_text, as: :text, input_html: {rows: 20, class: 'small markdown-editor'}
  = form.input :how_it_works, as: :text, input_html: {rows: 20, class: 'markdown-editor'}

  fieldset
    h3 = t('.start_content')
    = form.simple_fields_for :start_content, OpenStruct.new(resource.start_content) do |fs|
      = form.input :start_hero_image, as: :file
      = fs.input :title
      = fs.input :subtitle

      - for step in [:first, :second, :third]
        .row
          .large-4.columns
            = fs.input "#{step}_step_icon"
          .large-4.columns
            = fs.input "#{step}_step_title"
          .large-4.columns
            = fs.input "#{step}_step_description"

      = fs.input :start_primary_content, as: :text, input_html: {rows: 20, class: 'markdown-editor'}
      = fs.input :start_secondary_content, as: :text, input_html: {rows: 20, class: 'markdown-editor'}

  fieldset
    h3 = t('.success_content')
    = form.simple_fields_for :success_content, OpenStruct.new(resource.success_content) do |fs|
      = fs.input :main_text, as: :text, input_html: {rows: 20, class: 'markdown-editor'}
      = fs.input :button_text
      = fs.input :button_link

  = form.button :submit, class: 'button', data: { disable_with: t('words.sending') }

app/views/neighborly/admin/channels/edit.html.slim
- @title = t('.title')
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      h3 = @title
      = render 'form'

app/views/neighborly/admin/channels/index.html.slim
- @title = t('.title')
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      .text-right
        = link_to t('.new'), new_channel_path, class: 'button'
      .data-table
        = paginate collection
        - if collection.empty?
          = t('.no_channels')
        - else
          table
            thead
              tr
                th style="width: 200px;"
                  = t('.name')
                th
                  = t('.members')
                th
                  = t('.permalink')
                th
                  = t('.created_at')
                th
                  = t('.state')
                th
            tbody
              - collection.each do |channel|
                tr id=channel.id
                  td = channel.name
                  td
                    - if channel.members.any?
                      ul
                        - for user in channel.members
                          li = link_to user.display_name, main_app.user_path(user)
                    = link_to t('.manage_members'), channel_members_path(channel), class: 'button secondary tiny'
                  td = channel.permalink
                  td = channel.created_at.to_date
                  td = channel.state
                  td
                    .text-right
                      = link_to t('.edit'), edit_channel_path(channel), class: 'button tiny'
                      | &nbsp;
                      = link_to t('.destroy'), channel_path(channel), method: :delete, confirm: t('neighborly.admin.confirm_dialog'), class: 'button tiny alert'
                      | &nbsp; &nbsp;
                      = link_to 'javascript:void(0);', class: 'button tiny secondary', data: {dropdown: "dropdown-#{channel.id}"} do
                        i.icon-et-down-dir
                      ul.text-left[id="dropdown-#{channel.id}" data-dropdown-content class="f-dropdown"]
                        li
                          - if channel.online?
                            = link_to push_to_draft_channel_path(channel), method: :put do
                              = t('.push_to_draft')
                          - if channel.draft?
                            = link_to push_to_online_channel_path(channel), method: :put do
                              = t('.push_to_online')

        = paginate collection

app/views/neighborly/admin/channels/new.html.slim
- @title = t('.title')
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      h3 = @title
      = render 'form'