config/routes.rb
Neighborly::Admin::Engine.routes.draw do
  root to: 'dashboard#index'
  resources :tags, except: [:show]
  resources :press_assets, except: [:show]
  resources :financials, only: [ :index ]
  resources :users, only: [ :index ]

  resources :channels, except: [:show] do
    member do
      put 'push_to_draft'
      put 'push_to_online'
    end

    resources :members, only: [:index, :new, :create, :destroy], controller: 'channels/members'
  end

  resources :projects, only: [ :index, :update, :destroy ] do
    member do
      put 'launch'
      put 'reject'
      put 'push_to_draft'
      put 'approve'
      get 'populate_contribution'
      post 'populate'
    end
  end

  resources :contributions, only: [ :index, :update ] do
    member do
      put 'confirm'
      put 'pendent'
      put 'change_reward'
      put 'refund'
      put 'hide'
      put 'cancel'
      put 'push_to_trash'
    end
  end

  namespace :reports do
    resources :contribution_reports, only: [ :index ]
    resources :funding_raised_per_project_reports, only: [ :index ]
    resources :statistics, only: [ :index ]
  end

  resources :contacts, only: [:index, :show]
end

app/controllers/neighborly/admin/press_assets_controller.rb
module Neighborly::Admin
  class PressAssetsController < BaseController
    actions :all, except: [:show]

    def create
      create! { press_assets_path }
    end

    def update
      update! { press_assets_path }
    end

    def destroy
      destroy! { press_assets_path }
    end

    protected
    def collection
      @press_assets ||= apply_scopes(end_of_association_chain).page(params[:page])
    end

    def permitted_params
      params.permit({ press_asset: PressAsset.attribute_names.map(&:to_sym) })
    end
  end
end

app/views/neighborly/admin/press_assets/_form.html.slim
- content_for :title, t('.title')
= simple_form_for resource, url: (resource.persisted? ? press_asset_path(resource) : press_assets_path) do |f|
  = f.input :title
  = f.input :url
  = f.input :image, as: :file, required: !resource.persisted?
  - if resource.image.present?
    .image-preview
      = image_tag(resource.image.thumb.url, size: '170x60')
      br/
      br/
  = f.button :submit, data: { disable_with: I18n.t('words.sending') }

app/views/neighborly/admin/press_assets/edit.html.slim
- content_for :title, t('.title')
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      .title
        h3 = @title = t('.title')

      = render 'form'

app/views/neighborly/admin/press_assets/index.html.slim
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      .text-right
        = link_to t('.new'), new_press_asset_path, class: 'button'
      .data-table
        = paginate @press_assets
        - if @press_assets.empty?
          = t('.no_press_assets')
        - else
          table
            thead
              tr
                th style="width: 200px;"
                  = t('.title')
                th= t('.url')
                th= t('.image')
                th
            tbody
              - @press_assets.each do |press_asset|
                tr id=press_asset.id
                  td = press_asset.title
                  td = link_to(press_asset.url, target: 'blank')
                  td = image_tag(press_asset.image.thumb.url, width: 100)
                  td
                    .pull-right
                      = link_to t('.edit'), edit_press_asset_path(press_asset), class: 'button tiny'
                      | &nbsp;
                      = link_to t('.destroy'), press_asset_path(press_asset), method: :delete, confirm: t('words.confirm'), class: 'button tiny alert'

        = paginate @press_assets

app/views/neighborly/admin/press_assets/new.html.slim
- content_tag :title, t('.title')
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      .title 
        h3 = @title = t('.title')

      = render 'form'