config/routes.rb
Neighborly::Admin::Engine.routes.draw do
  root to: 'dashboard#index'
  resources :tags, except: [:show]
  resources :press_assets, except: [:show]
  resources :financials, only: [ :index ]
  resources :users, only: [ :index ]

  resources :channels, except: [:show] do
    member do
      put 'push_to_draft'
      put 'push_to_online'
    end

    resources :members, only: [:index, :new, :create, :destroy], controller: 'channels/members'
  end

  resources :projects, only: [ :index, :update, :destroy ] do
    member do
      put 'launch'
      put 'reject'
      put 'push_to_draft'
      put 'approve'
      get 'populate_contribution'
      post 'populate'
    end
  end

  resources :contributions, only: [ :index, :update ] do
    member do
      put 'confirm'
      put 'pendent'
      put 'change_reward'
      put 'refund'
      put 'hide'
      put 'cancel'
      put 'push_to_trash'
    end
  end

  namespace :reports do
    resources :contribution_reports, only: [ :index ]
    resources :funding_raised_per_project_reports, only: [ :index ]
    resources :statistics, only: [ :index ]
  end

  resources :contacts, only: [:index, :show]
end

app/controllers/neighborly/admin/projects_controller.rb
module Neighborly::Admin
  class ProjectsController < BaseController
    defaults finder: :find_by_permalink!

    has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
    has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

    before_filter do
      @total_projects = Project.count
    end

    [:launch, :reject, :push_to_draft, :approve].each do |name|
      define_method name do
        @project = Project.find_by_permalink params[:id]
        @project.send("#{name.to_s}!")
        redirect_to :back
      end
    end

    def populate
      if params[:user][:id].present?
        @user = User.find(params[:user][:id])
      else
        @user = create_user
      end

      @contribution = build_contribution(@user)

      if @user.valid? and @contribution.valid?
        @user.save!
        @contribution.save!
        redirect_to populate_contribution_project_path(resource), flash: { success: 'Success!' }
      else
        flash.alert = (@user.errors.full_messages +
                       @contribution.errors.full_messages).to_sentence
        render :populate_contribution
      end
    end

    def destroy
      resource.push_to_trash! if resource.can_push_to_trash?
      redirect_to projects_path
    end

    protected
    def collection
      @projects = apply_scopes(end_of_association_chain).order('projects.created_at desc').without_state('deleted').page(params[:page])
    end

    def create_user
      password = Devise.friendly_token
      user = User.new(user_params[:user])
      user.email = "#{Devise.friendly_token}@populate.user"
      user.password = password
      user.password_confirmation = password
      user.profile_type = user_params[:user][:profile_type]
      user
    end

    def build_contribution(user)
      contribution = resource.contributions.new(contribution_params[:contribution])
      contribution.payment_method = 'PrePopulate'
      contribution.state = 'confirmed'
      contribution.user = user
      contribution
    end

    def user_params
      params.permit({ user: User.attribute_names.map(&:to_sym) })
    end

    def contribution_params
      params.permit({ contribution: Contribution.attribute_names.map(&:to_sym) })
    end

    def permitted_params
      params.permit({ project: Project.attribute_names.map(&:to_sym) })
    end
  end
end

app/views/neighborly/admin/projects/index.html.slim
- @title = t('.title')
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      h4
        strong= "#{@total_projects} "
        = t('.total_projects')

      .filters
        = form_tag projects_path, method: :get, class: 'form-horizontal' do |f|
          = hidden_field_tag :order_by, params[:order_by]
          .row
            .large-3.columns
              = label_tag :by_id, t('.id')
              = text_field_tag :by_id, params[:by_id], class: 'input-small'

            - [:between_created_at, :between_expires_at, :between_online_date].each do |between_field|
              .large-3.columns
                = label_tag "#{between_field}_start_at".to_sym, t(".#{between_field}")
                = text_field_tag "#{between_field}[start_at]", (params[between_field][:start_at] if params[between_field].present?)
                | &nbsp;
                | &nbsp;
                = text_field_tag "#{between_field}[ends_at]", (params[between_field][:ends_at] if params[between_field].present?)

          .row
            .large-4.columns
              = label_tag :pg_search, t('.project')
              = text_field_tag :pg_search, params[:pg_search]
            .large-4.columns
              = label_tag :with_state, t('.with_state')
              = select_tag :with_state, options_for_select(Project.state_names, params[:with_state]), include_blank: true
            .large-4.columns
              = label_tag :by_category_id, t('.by_category')
              = select_tag :by_category_id, options_from_collection_for_select(Category.all, :id, :name_pt,params[:by_category_id]), include_blank: true
          .row
            .large-6.columns
              = label_tag :user_name_contains, t('.user')
              = text_field_tag :user_name_contains, params[:user_name_contains]
            .large-6.columns
              = label_tag :by_user_email, t('.by_user_email')
              = text_field_tag :by_user_email, params[:by_user_email]

          .row
            .large-12.columns.text-right
              = submit_tag t('.submit'), class: 'button'
        .row
          .large-6.columns.text-left
              = paginate @projects
          .large-6.columns.text-right
            = pluralize_without_number @projects.to_a.size, t('words.found_singular'), t('words.found_plural')
            | &nbsp;
            strong = @projects.to_a.size
            | &nbsp;
            = pluralize_without_number(@projects.to_a.size, t('words.project_singular'), t('words.project_plural')).downcase
      .data-table
        - if @projects.empty?
          = t('.no_projects')
        - else
          table.small
            thead
              tr
                th style="width: 200px;"
                  = t('.name')
                th= t('.category')
                th= t('.user_id')
                th
                  a data-sort="goal" href='#'= t('.goal')
                  span.sort-order
                th
                  a data-sort="pt.progress" href='#'= t('.pledged')
                  span.sort-order
                th
                  a data-sort="pt.total_contributions" href='#'= t('.total_contributions')
                  span.sort-order
                th= t('.recommended')
                th= t('.featured')
                th= t('.home_page')
                th
                  a data-sort="online_date" href='#'= t('.online_date')
                  span.sort-order
                th
                  a data-sort="projects.expires_at" href='#'= t('.expires_at')
                  span.sort-order
                th= t('.state')
                th
            tbody
              - @projects.each do |project|
                tr id=project.id
                  td
                    = link_to project.name, main_app.project_path(project)
                    - if project.channels.present?
                      | &nbsp;
                      - project.channels.each do |channel|
                        span.label.label-inverse= channel.name
                        | &nbsp;
                  td= project.category
                  td= best_in_place project, :user_id, type: :input
                  td= best_in_place project, :goal, type: :input, display_as: :display_goal
                  td= "#{project.display_pledged} (#{project.progress}%)"
                  td= project.total_contributions
                  td.checkbox= best_in_place project, :recommended, type: :checkbox, collection: [t('words._no'), t('words._yes')]
                  td.checkbox= best_in_place project, :featured, type: :checkbox, collection: [t('words._no'), t('words._yes')]
                  td.checkbox= best_in_place project, :home_page, type: :checkbox, collection: [t('words._no'), t('words._yes')]
                  td= project.online_date.to_date if project.online_date
                  td= project.display_expires_at
                  td
                    - if project.online?
                      span.label.label-online= project.state
                    - elsif project.successful?
                      span.label.label-success= project.state
                    - elsif project.failed? or project.rejected?
                      span.label.label-important= project.state
                    - elsif project.waiting_funds?
                      span.label.label-warning= project.state
                    - else
                      span.label= project.state
                  td
                    = link_to 'javascript:void(0);', class: 'button tiny secondary', data: {dropdown: "dropdown-#{project.id}"} do
                      i.icon-et-down-dir
                    ul[id="dropdown-#{project.id}" data-dropdown-content class="f-dropdown"]
                      li
                        = link_to populate_contribution_project_path(project) do
                          = t('.populate_contribution')
                      - if project.can_approve?
                        li
                          = link_to  approve_project_path(project), method: :put  do
                            = t('.approve')

                      - if project.can_launch?
                        li
                          = link_to launch_project_path(project), method: :put do
                            = t('.launch')

                      - if project.can_reject?
                        li
                          = link_to reject_project_path(project), method: :put  do
                            = t('.reject')

                      - if project.can_push_to_draft?
                        li
                          = link_to  push_to_draft_project_path(project), method: :put  do
                            = t('.send_to_draft')

                      - if project.can_push_to_trash?
                        li
                          = link_to project_path(project), method: :delete, data: {confirm: t('neighborly.admin.confirm_dialog')} do
                            = t('.send_to_trash')
        = paginate @projects

app/views/neighborly/admin/projects/populate_contribution.html.slim
- content_for :title, t('.title')
.admin
  .row
    = render 'neighborly/admin/layouts/menu'
    section.content.large-12.columns
      h3 = "Pre populate contributions on #{resource.name}"

      = form_tag populate_project_path, :multipart => true do
        fieldset.first
          legend
            | Create a new guest user
          .input
            = label_tag 'user[name]', 'Name'
            = text_field_tag 'user[name]'
          .input
            = label_tag 'user[profile_type]', 'Profile Type'
            .row
              label.large-2.columns
                = radio_button_tag 'user[profile_type]', 'personal', true
                | &nbsp;
                | Person
                | &nbsp;
              label.large-10.columns
                = radio_button_tag 'user[profile_type]', 'organization'
                | &nbsp;
                | Organization (Company, Foundation, etc...)
          .input
            = label_tag 'user[uploaded_image]', 'Image'
            = file_field_tag 'user[uploaded_image]'
        fieldset.last
          legend
            | Or add this contribution a registered user
          .input
            = label_tag 'user[id]', 'User ID'
            = text_field_tag 'user[id]'
        .clearfix
        hr
        .input
          = label_tag 'contribution[reward_id]', 'Reward value'
          = select_tag 'contribution[reward_id]', options_from_collection_for_select(resource.rewards.not_soon, "id", "display_minimum"), :include_blank => true
        .input
          = label_tag 'contribution[value]', 'Value'
          = text_field_tag 'contribution[value]'
        .input
          = label_tag 'contribution[anonymous]', 'Anonymous'
          = check_box_tag 'contribution[anonymous]', true, checked: true
        .input
          = submit_tag 'Submit', class: 'button'